### ISSUE TITLE
Roadmap 

### ISSUE THREAD

**Issue by mfreeman451** [carverauto/threadr#10]
## ToDo

* Relationship Inference Refinement 

- [ ] NLP sentiment analysis
- [ ] interaction frequency analysis
- [ ] temporal decay models

* Interactive visualizations 

- [ ] D3.js
- [ ] enable filtering, weighting, and cluster highlighting

* Logging and Monitoring

- [ ] otel

* TDD

- [ ] need tests and unit tests

* Neo4j

- [ ] Create index on User.name for faster lookups
- [ ] Batching operations for batch loading of chat logs?

* Bot Filtering

- [ ] abnormal activity pattern detection
- [ ]
